services:
  app:
    build: .
    ports:
      - "9600:9600"
    volumes:
      - ./data:/app/data
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "${PORT:-9600}"]


